"""How a theme actually gets applied: the one seam between the picker and the
reverse proxy.

A backend does two things: make a theme the live one (apply), and rewrite the
proxy's config for the current theme plus per-app pins (set_pins). Everything
else -- the allowlist, history, the schedule, the page -- is the same whichever
backend is configured (`backend.type` in picker.yml).

traefik-file (the default) needs nothing but this package: it records the live
theme in current-theme.env and writes one traefik-themepark middleware per app
into a file Traefik's file provider watches -- the same files, format and
atomic write that theme-switcher's set-theme.sh + generate-themes-yml.py
produce, so the two can be used side by side.

script delegates to those two scripts instead, for a setup that wants its own
hooks around a change.

Callers validate the theme against the allowlist first; backends re-check
that it is a plain name anyway, since the name ends up in a file Traefik
loads.
"""

import os
import subprocess
import sys
import tempfile
import threading
from pathlib import Path

import yaml

from . import config

_LOCK = threading.Lock()


class ApplyError(Exception):
    """Applying failed; the message is safe to show to the person who asked."""


def _plain(theme):
    if not isinstance(theme, str) or not config.SAFE_NAME.match(theme):
        raise ApplyError(f"not a plain theme name: {theme!r}")
    return theme


def _atomic_write(path, text):
    """Write via a temp file in the same directory + os.replace(): a watcher
    (Traefik's file provider) only ever sees the old or the new file, never a
    truncated one -- a plain open(path, "w") briefly 502'd every themed
    router when this was done by the generator."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(text)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise


def read_current(state_file):
    """CURRENT_THEME from the state file, or "" if absent."""
    try:
        for line in Path(state_file).read_text().splitlines():
            if line.startswith("CURRENT_THEME="):
                return line.split("=", 1)[1].strip()
    except OSError:
        pass
    return ""


def write_current(state_file, theme):
    """Set CURRENT_THEME, keeping any other lines (comments) as they are --
    what set-theme.sh does with sed."""
    path = Path(state_file)
    try:
        lines = path.read_text().splitlines()
    except FileNotFoundError:
        lines = []
    for i, line in enumerate(lines):
        if line.startswith("CURRENT_THEME="):
            lines[i] = f"CURRENT_THEME={theme}"
            break
    else:
        lines.append(f"CURRENT_THEME={theme}")
    _atomic_write(path, "\n".join(lines) + "\n")


HEADER = (
    "# AUTO-GENERATED by the theme picker's traefik-file backend -- do not edit\n"
    "# by hand. Change the theme in the picker (or theme-switcher's set-theme.sh,\n"
    "# which writes the same file); change which apps are themed in apps.yml.\n"
    "#\n"
    "# Each app's OTHER middlewares (auth, CSP headers, etc.) live in that\n"
    "# app's own router config, chained alongside <name>-theme@file in its\n"
    "# router's middlewares -- this file only defines the theme-park plugin\n"
    "# blocks themselves.\n"
)


def render_middlewares(apps, theme, pins, base_url):
    """The Traefik dynamic config, as a dict: one themepark middleware per
    app, the pinned theme where there is one, else `theme`."""
    middlewares = {}
    for app in apps:
        cfg = {"app": app["theme_app"], "theme": pins.get(app["name"], theme), "baseUrl": base_url}
        if app.get("addons"):
            cfg["addons"] = list(app["addons"])
        middlewares[f"{app['name']}-theme"] = {"plugin": {"themepark": cfg}}
    return {"http": {"middlewares": middlewares}}


class TraefikFile:
    name = "traefik-file"

    def __init__(self, output_file, state_file, default_theme, apps, pins, base_url):
        # apps, pins and base_url are callables, read at each write: apps.yml,
        # the pins file and config.env can all change while the picker runs.
        self.output_file, self.state_file = Path(output_file), Path(state_file)
        self.default_theme = default_theme
        self._apps, self._pins, self._base_url = apps, pins, base_url

    def apply(self, theme, ignore_pins=False):
        theme = _plain(theme)
        with _LOCK:
            self._write(theme, ignore_pins)          # proxy first: a failure leaves state alone
            write_current(self.state_file, theme)

    def set_pins(self):
        with _LOCK:
            self._write(read_current(self.state_file) or self.default_theme, False)

    def _write(self, theme, ignore_pins):
        base = self._base_url()
        if not base:
            raise ApplyError("no theme-park URL (theme_park_url in picker.yml, or BASE_URL in config.env)")
        apps = self._apps()
        if not apps:
            raise ApplyError("no themed apps defined (apps.yml)")
        pins = {} if ignore_pins else {k: _plain(v) for k, v in self._pins().items()}
        body = yaml.safe_dump(render_middlewares(apps, theme, pins, base),
                              default_flow_style=False, sort_keys=False)
        try:
            _atomic_write(self.output_file, HEADER + body)
        except OSError as e:
            raise ApplyError(f"could not write {self.output_file.name}: {e.strerror or e}")


class Script:
    name = "script"

    def __init__(self, set_theme, generator, cwd):
        self.set_theme, self.generator, self.cwd = Path(set_theme), Path(generator), Path(cwd)

    def _run(self, argv, what, ignore_pins=False):
        env = dict(os.environ, THEME_IGNORE_OVERRIDES="1" if ignore_pins else "0")
        r = subprocess.run(argv, cwd=self.cwd, env=env, capture_output=True, text=True, timeout=30)
        if r.returncode != 0:
            raise ApplyError(f"{what} failed: {r.stderr.strip()[-300:]}")

    def apply(self, theme, ignore_pins=False):
        # An argument list, never shell=True: the name cannot become a command.
        self._run(["/bin/bash", str(self.set_theme), _plain(theme)], "set-theme.sh", ignore_pins)

    def set_pins(self):
        self._run([sys.executable, str(self.generator)], "generator")


def get():
    """The configured backend, built from current settings."""
    from . import state                            # state imports this module
    s = config.SETTINGS
    if s["backend.type"] == "script":
        return Script(config.SET_THEME_SCRIPT, config.THEME_DIR / "generate-themes-yml.py", config.THEME_DIR)
    return TraefikFile(output_file=config.output_file(), state_file=config.CONFIG_FILE,
                       default_theme=s["backend.default_theme"], apps=state.load_apps,
                       pins=state.read_overrides, base_url=config.base_url)
